<footer class="footer">
  <p class="footer__contacts">
    <span class="footer__contacts__text">Казахстан, г.&nbsp;Астана, ул.&nbsp;Кабанбай&nbsp;батыра,&nbsp;11, Офис&nbsp;№1</span>
    <span class="footer__contacts__text">Тел: +7 717 268-88-73</span>
  </p>
  <a href="/" class="footer__company-name">PRESTIGE BUILDING GROUP</a>
  <p class="footer__copyright">&copy; 2015 г. Все права защищены</p>
</footer>
