<footer class="footer">
  <p class="footer__contacts">
    <span class="footer__contacts__text">Казахстан, г.&nbsp;Астана, ул.&nbsp;Сыганак, 25, 13 этаж, БЦ &laquo;Ансар&raquo;</span>
    <span class="footer__contacts__text">Тел: +77172550517,  Факс: +77172550516</span>
  </p>
  <a href="/" class="footer__company-name">Prestige building group</a>
  <p class="footer__copyright">&copy; 2015 г. Все права защищены</p>
</footer>
