<section class="header <?php if($_SERVER['SCRIPT_NAME']=='/home.php') echo 'header_transparent'; ?>">
  <span class="header__menu-btn">
    <i class="header__menu-btn__line header__menu-btn__line_first"></i>
    <i class="header__menu-btn__line header__menu-btn__line_middle"></i>
    <i class="header__menu-btn__line header__menu-btn__line_last"></i>
  </span>
  <a href="home.php" class="header__logo"><img src="build/images/logo.svg" /></a>

  <section class="header__menu">
    <div class="header__menu__background"></div>
    <!-- Header Menu Wrapper-->
    <div class="header__menu__wrapper">
      <div class="header__menu__content">
        <span class="header__menu__close"></span>
        <div class="header__menu__item">
          <p class="header__menu__item__link header__menu__item__link_disabled header__menu__item__link_about">О компании</p>
          <ul class="header__menu__submenu">
            <li class="header__menu__submenu__item">
              <a href="" class="header__menu__submenu__item__link">О компании</a>
            </li>
            <li class="header__menu__submenu__item">
              <a href="" class="header__menu__submenu__item__link">Наша команда</a>
            </li>
            <li class="header__menu__submenu__item">
              <a href="" class="header__menu__submenu__item__link">Рекомендации</a>
            </li>
            <li class="header__menu__submenu__item">
              <a href="" class="header__menu__submenu__item__link">Корпоративная структура</a>
            </li>
            <li class="header__menu__submenu__item">
              <a href="" class="header__menu__submenu__item__link">История развития концерна</a>
            </li>
            <li class="header__menu__submenu__item">
              <a href="" class="header__menu__submenu__item__link">Сертификаты и лицензии</a>
            </li>
            <li class="header__menu__submenu__item">
              <a href="" class="header__menu__submenu__item__link">Партнеры</a>
            </li>
            <li class="header__menu__submenu__item">
              <a href="" class="header__menu__submenu__item__link">Общественная деятельность</a>
            </li>
            <li class="header__menu__submenu__item">
              <a href="" class="header__menu__submenu__item__link">Презентация</a>
            </li>
          </ul>
        </div>
        <div class="header__menu__item">
          <a href="" class="header__menu__item__link header__menu__item__link_projects">Проекты</a>
        </div>
        <div class="header__menu__item">
          <a href="" class="header__menu__item__link header__menu__item__link_news">Новости</a>
        </div>
        <div class="header__menu__item">
          <a href="" class="header__menu__item__link header__menu__item__link_services">Услуги</a>
        </div>
        <div class="header__menu__item">
          <a href="" class="header__menu__item__link header__menu__item__link_contacts">Контакты</a>
        </div>
      </div>
    </div>
    <!-- /Header Menu Wrapper-->
  </section>
</section>
