<head>
	<!-- Meta -->
	<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1" />
	<meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="format-detection" content="telephone=no" />
	<meta name="google" content="notranslate" />
	<!-- CSS -->
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:600,700,400,300&subset=cyrillic,latin' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
	<link href="build/css/style.css" rel="stylesheet" />
</head>
